using AnalogHub.Application.Common.Interfaces;

namespace AnalogHub.Infrastructure.AI.Mock;

/// <summary>
/// Demo-mode stand-in for <see cref="IChatCompletionService"/>. The RAG handler still does real
/// retrieval (pgvector cosine search via <see cref="MockEmbeddingService"/>'s vectors) — this only
/// fakes the final answer synthesis, quoting the first retrieved context snippet so the response
/// visibly reflects what was actually retrieved rather than being a static canned string.
/// </summary>
public sealed class MockChatCompletionService : IChatCompletionService
{
    public Task<string> CompleteAsync(string systemPrompt, string userPrompt, CancellationToken cancellationToken)
    {
        var firstSnippet = systemPrompt
            .Split('\n', StringSplitOptions.RemoveEmptyEntries)
            .FirstOrDefault(line => line.TrimStart().StartsWith('['));

        var answer = firstSnippet is null
            ? "[Demo mode] I don't have any knowledge base context to answer from yet. In a real " +
              "deployment with Gemini:ApiKey set, I'd search the knowledge base and answer with citations."
            : $"[Demo mode — mock answer] {Truncate(firstSnippet.Trim(), 280)} " +
              "This response was generated by the demo mock AI provider from the retrieved context above, " +
              "not a real language model. Set Gemini:ApiKey and UseMockAi:false for genuine answers.";

        return Task.FromResult(answer);
    }

    private static string Truncate(string text, int maxChars) =>
        text.Length <= maxChars ? text : text[..maxChars].TrimEnd() + "…";
}
