using AnalogHub.Application.Common.Interfaces;

namespace AnalogHub.Infrastructure.AI.Mock;

/// <summary>
/// Demo-mode stand-in for <see cref="IVisionAnalysisService"/> — returns one of a few realistic,
/// hand-written critiques (picked deterministically from the image URL, so the same photo always
/// gets the same result) instead of calling Gemini. Wired in when <c>UseMockAi</c> is true, so the
/// app is fully explorable straight from a GitHub clone with no API key.
/// </summary>
public sealed class MockVisionAnalysisService : IVisionAnalysisService
{
    private static readonly PhotoCritiqueResult[] Templates =
    [
        new(
            "mock-vision-v1",
            8,
            "Strong diagonal composition — the subject sits on the right third with the horizon " +
            "aligned along the lower third line, giving the frame good visual weight and a clear " +
            "sense of depth. Foreground framing elements guide the eye naturally toward the subject.",
            "Soft, directional light from camera-left models the subject's features well without " +
            "harsh shadows. Highlights are well controlled with no visible clipping; shadow detail " +
            "holds up, suggesting good exposure latitude from the film stock.",
            null,
            [
                "Try moving a half-step left to tuck the background pole behind the subject's shoulder.",
                "A touch more fill light on the shadow side would open up detail in the darker areas.",
                "Consider a slightly wider aperture next time to separate the subject from the background more."
            ],
            ["street", "available-light", "candid"],
            MockRawResponseJson),
        new(
            "mock-vision-v1",
            9,
            "Classic rule-of-thirds portrait framing with the subject's eyes on the upper power " +
            "point. Negative space on the left balances the frame nicely and gives the pose room to " +
            "breathe without feeling cramped.",
            "Key light appears to come from a large, soft source at roughly 45 degrees — the kind of " +
            "falloff that flatters facial contours. No visible flash artifacts; the catchlights in the " +
            "eyes suggest a window or diffused strobe.",
            "Shoulders are angled away from the camera with the face turned back toward the lens — a " +
            "flattering, classic pose. Hands are relaxed and out of frame, which keeps the composition clean.",
            [
                "Bring the horizon or background line further from the subject's head to avoid it appearing to merge.",
                "A slightly lower camera angle would elongate the pose even further.",
                "Try a second frame with a genuine smile for variety alongside this more contemplative look."
            ],
            ["portrait", "natural-light", "headshot"],
            MockRawResponseJson),
        new(
            "mock-vision-v1",
            6,
            "The frame is busy — several competing lines from the background architecture pull focus " +
            "away from the subject. A tighter crop would isolate the intended focal point more effectively.",
            "Contrasty midday light creates hard shadows across the scene. Highlight detail in the sky " +
            "looks close to blown, though the film's latitude may recover some of it in the scan.",
            null,
            [
                "Shoot earlier or later in the day for softer, more directional light.",
                "Move closer or use a longer lens to simplify the background.",
                "Watch the frame edges for distracting elements before releasing the shutter."
            ],
            ["landscape", "midday", "architecture"],
            MockRawResponseJson),
    ];

    private const string MockRawResponseJson = """{"mock":true,"note":"Generated by the demo mock AI provider — set Gemini:ApiKey and UseMockAi:false for real analysis."}""";

    public Task<PhotoCritiqueResult> AnalyzePhotoAsync(
        string imageUrl,
        VisionAnalysisContext context,
        CancellationToken cancellationToken)
    {
        // imageUrl is a freshly presigned URL — its signature/expiry query string differs on every
        // call even for the same photo, so hashing the full URL would pick a different template each
        // time despite the class doc's "same photo always gets the same result" promise. Hash only
        // the stable object path instead.
        var stablePath = imageUrl.Split('?', 2)[0];
        var index = Math.Abs(stablePath.GetHashCode(StringComparison.Ordinal)) % Templates.Length;
        return Task.FromResult(Templates[index]);
    }
}
