// <auto-generated />
using System;
using AnalogHub.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace AnalogHub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AnalogHubDbContext))]
    partial class AnalogHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnalogHub.Domain.Entities.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CoverPhotoId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CoverPhotoId");

                    b.ToTable("Albums", (string)null);
                });

            modelBuilder.Entity("AnalogHub.Domain.Entities.AlbumPhoto", b =>
                {
                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PhotoId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("AlbumId", "PhotoId");

                    b.HasIndex("PhotoId");

                    b.HasIndex("AlbumId", "SortOrder");

                    b.ToTable("AlbumPhotos", (string)null);
                });

            modelBuilder.Entity("AnalogHub.Domain.Entities.FilmRoll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("CameraBodyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateDeveloped")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateFinished")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateLoaded")
                        .HasColumnType("date");

                    b.Property<string>("DeveloperNotes")
                        .HasColumnType("text");

                    b.Property<int?>("ExposedAtIso")
                        .HasColumnType("integer");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("FrameCount")
                        .HasColumnType("integer");

                    b.Property<string>("LabName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("NominalIso")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CameraBodyId");

                    b.HasIndex("Status");

                    b.ToTable("FilmRolls", (string)null);
                });

            modelBuilder.Entity("AnalogHub.Domain.Entities.Gear.Gear", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("AcquiredOn")
                        .HasColumnType("date");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GearType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MountType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Brand", "Model");

                    b.ToTable("Gear", (string)null);

                    b.HasDiscriminator<string>("GearType").HasValue("Gear");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AnalogHub.Domain.Entities.KnowledgeChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(768)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TokenCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("DocumentTitle", "ChunkIndex");

                    b.ToTable("KnowledgeChunks", (string)null);
                });

            modelBuilder.Entity("AnalogHub.Domain.Entities.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlurHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("CameraBodyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CaptureDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("FilmRollId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FlashId")
                        .HasColumnType("uuid");

                    b.Property<int?>("FrameNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("HeightPx")
                        .HasColumnType("integer");

                    b.Property<Guid?>("LensId")
                        .HasColumnType("uuid");

                    b.Property<string>("OriginalStorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PreviewStorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ProcessingError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<byte>("Rating")
                        .HasColumnType("smallint");

                    b.Property<string>("ThumbnailStorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("WidthPx")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CameraBodyId");

                    b.HasIndex("CaptureDateUtc");

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("FilmRollId");

                    b.HasIndex("FlashId");

                    b.HasIndex("LensId");

                    b.HasIndex("ProcessingStatus");

                    b.ToTable("Photos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Photos_Rating_Range", "\"Rating\" >= 0 AND \"Rating\" <= 5");
                        });
                });

            modelBuilder.Entity("AnalogHub.Domain.Entities.PhotoAiCritique", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompositionNotes")
                        .HasColumnType("text");

                    b.Property<int?>("CompositionScore")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LightingNotes")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PhotoId")
                        .HasColumnType("uuid");

                    b.Property<string>("PosingNotes")
                        .HasColumnType("text");

                    b.Property<string>("RawResponseJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RecommendationsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SuggestedTagsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId")
                        .IsUnique();

                    b.ToTable("PhotoAiCritiques", (string)null);
                });

            modelBuilder.Entity("AnalogHub.Domain.Entities.PhotoTag", b =>
                {
                    b.Property<Guid>("PhotoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAiSuggested")
                        .HasColumnType("boolean");

                    b.HasKey("PhotoId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PhotoTags", (string)null);
                });

            modelBuilder.Entity("AnalogHub.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("AnalogHub.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AnalogHub.Domain.Entities.Gear.CameraBody", b =>
                {
                    b.HasBaseType("AnalogHub.Domain.Entities.Gear.Gear");

                    b.Property<int[]>("SupportedFormats")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasDiscriminator().HasValue("CameraBody");
                });

            modelBuilder.Entity("AnalogHub.Domain.Entities.Gear.Flash", b =>
                {
                    b.HasBaseType("AnalogHub.Domain.Entities.Gear.Gear");

                    b.Property<decimal?>("GuideNumber")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<bool>("HasTtl")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("Flash");
                });

            modelBuilder.Entity("AnalogHub.Domain.Entities.Gear.Lens", b =>
                {
                    b.HasBaseType("AnalogHub.Domain.Entities.Gear.Gear");

                    b.Property<decimal?>("FocalLengthMaxMm")
                        .HasPrecision(6, 1)
                        .HasColumnType("numeric(6,1)");

                    b.Property<decimal?>("FocalLengthMinMm")
                        .HasPrecision(6, 1)
                        .HasColumnType("numeric(6,1)");

                    b.Property<decimal?>("MaxAperture")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)");

                    b.Property<decimal?>("MinAperture")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)");

                    b.HasDiscriminator().HasValue("Lens");
                });

            modelBuilder.Entity("AnalogHub.Domain.Entities.Album", b =>
                {
                    b.HasOne("AnalogHub.Domain.Entities.Photo", "CoverPhoto")
                        .WithMany()
                        .HasForeignKey("CoverPhotoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CoverPhoto");
                });

            modelBuilder.Entity("AnalogHub.Domain.Entities.AlbumPhoto", b =>
                {
                    b.HasOne("AnalogHub.Domain.Entities.Album", "Album")
                        .WithMany("AlbumPhotos")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnalogHub.Domain.Entities.Photo", "Photo")
                        .WithMany("AlbumPhotos")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("AnalogHub.Domain.Entities.FilmRoll", b =>
                {
                    b.HasOne("AnalogHub.Domain.Entities.Gear.CameraBody", "CameraBody")
                        .WithMany("FilmRolls")
                        .HasForeignKey("CameraBodyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CameraBody");
                });

            modelBuilder.Entity("AnalogHub.Domain.Entities.Photo", b =>
                {
                    b.HasOne("AnalogHub.Domain.Entities.Gear.CameraBody", "CameraBody")
                        .WithMany("Photos")
                        .HasForeignKey("CameraBodyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AnalogHub.Domain.Entities.FilmRoll", "FilmRoll")
                        .WithMany("Photos")
                        .HasForeignKey("FilmRollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnalogHub.Domain.Entities.Gear.Flash", "Flash")
                        .WithMany("Photos")
                        .HasForeignKey("FlashId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AnalogHub.Domain.Entities.Gear.Lens", "Lens")
                        .WithMany("Photos")
                        .HasForeignKey("LensId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("AnalogHub.Domain.ValueObjects.ExifData", "Exif", b1 =>
                        {
                            b1.Property<Guid>("PhotoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Aperture")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Exif_Aperture");

                            b1.Property<bool?>("FlashFired")
                                .HasColumnType("boolean")
                                .HasColumnName("Exif_FlashFired");

                            b1.Property<decimal?>("FocalLengthMm")
                                .HasPrecision(6, 1)
                                .HasColumnType("numeric(6,1)")
                                .HasColumnName("Exif_FocalLengthMm");

                            b1.Property<double?>("GpsLatitude")
                                .HasColumnType("double precision")
                                .HasColumnName("Exif_GpsLatitude");

                            b1.Property<double?>("GpsLongitude")
                                .HasColumnType("double precision")
                                .HasColumnName("Exif_GpsLongitude");

                            b1.Property<int?>("IsoUsed")
                                .HasColumnType("integer")
                                .HasColumnName("Exif_IsoUsed");

                            b1.Property<string>("MeteringMode")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Exif_MeteringMode");

                            b1.Property<string>("ScannerModel")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Exif_ScannerModel");

                            b1.Property<string>("ShutterSpeed")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Exif_ShutterSpeed");

                            b1.HasKey("PhotoId");

                            b1.ToTable("Photos");

                            b1.WithOwner()
                                .HasForeignKey("PhotoId");
                        });

                    b.Navigation("CameraBody");

                    b.Navigation("Exif")
                        .IsRequired();

                    b.Navigation("FilmRoll");

                    b.Navigation("Flash");

                    b.Navigation("Lens");
                });

            modelBuilder.Entity("AnalogHub.Domain.Entities.PhotoAiCritique", b =>
                {
                    b.HasOne("AnalogHub.Domain.Entities.Photo", "Photo")
                        .WithOne("Critique")
                        .HasForeignKey("AnalogHub.Domain.Entities.PhotoAiCritique", "PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("AnalogHub.Domain.Entities.PhotoTag", b =>
                {
                    b.HasOne("AnalogHub.Domain.Entities.Photo", "Photo")
                        .WithMany("PhotoTags")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnalogHub.Domain.Entities.Tag", "Tag")
                        .WithMany("PhotoTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("AnalogHub.Domain.Entities.Album", b =>
                {
                    b.Navigation("AlbumPhotos");
                });

            modelBuilder.Entity("AnalogHub.Domain.Entities.FilmRoll", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("AnalogHub.Domain.Entities.Photo", b =>
                {
                    b.Navigation("AlbumPhotos");

                    b.Navigation("Critique");

                    b.Navigation("PhotoTags");
                });

            modelBuilder.Entity("AnalogHub.Domain.Entities.Tag", b =>
                {
                    b.Navigation("PhotoTags");
                });

            modelBuilder.Entity("AnalogHub.Domain.Entities.Gear.CameraBody", b =>
                {
                    b.Navigation("FilmRolls");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("AnalogHub.Domain.Entities.Gear.Flash", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("AnalogHub.Domain.Entities.Gear.Lens", b =>
                {
                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
